### ISSUE TITLE
This Extension Is literally broken... Commands are not Registered Properly 

### ISSUE THREAD

**Issue by mowmowkittycat** [bitburner-official/bitburner-vscode#25]
Yea as the title says the extension is literally broken. I had to change source code of this extension to make it work, and it was really easy. The only issue with this is that the extension ID is not used properly in the code which is absolute bonkers that you guys failed to check that.

**Comment by OxSon** [comment]
If it's easy, why don't you submit a patch instead of opening an issue that does nothing but contribute to noise and insult?

Bugs and mistakes are the nature of software. When you find solutions to problems, you share them, not complain that the problem existed in the first place.

**Comment by mowmowkittycat** [comment]
nah i dont think i will
