### ISSUE TITLE
A way to ignore some files/folder to push (node_modules for example) ?

### ISSUE THREAD

**Issue by Ikaer** [bitburner-official/bitburner-vscode#4]
Hi,

Is there a way to ignore some files or folders when using the command "BitBurner: Push all files to the game". I would like to exclude my node_modules folder, it makes the games unresponsive for a few minutes when I do that.

**Comment by hexnaught** [comment]
If you change your `scriptRoot` in the extension settings from the default `./` to be `./src/` and put all of your files in there, or if your building from `.ts` files, `./dist/` or similar should it will then push just the files you need to in to the game.

The push all files command works based off of this `scriptRoot` setting.

**Comment by Ikaer** [comment]
Nice thanks!
